version: '3'

services:
  # API
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: filme/api
    container_name: api
    restart: unless-stopped
    ports:
        - 8000:8000
    environment:
      SERVICE_NAME: api
    working_dir: /var/www
    volumes:
      - ./api/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - filmes
  
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filmes
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - filmes
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - filmes
networks:
  filmes:
     driver: bridge
volumes:
  db_data: